//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 08:35:47 AM CEST 
//


package se.vgregion.kivtools.hriv.intsvc.ws.domain.eniro;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;



/**
 * <p>Java class for UnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Id"/>
 *         &lt;element name="ParentUnitId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}OrgNo" minOccurs="0"/>
 *         &lt;element ref="{}Name"/>
 *         &lt;element name="Management" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute ref="{}Visibility"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}Description" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Image" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{}Label"/>
 *                     &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                   &lt;attribute ref="{}Visibility"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}Address" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}Telephone" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}E-alias" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="VisitingConditions" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="VisitingHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="DropInHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="VisitingRules" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute ref="{}Visibility"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="BusinessClassification" maxOccurs="unbounded" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="BCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="BCName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;attribute ref="{}Visibility"/>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="Person" type="{}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="Locality" minOccurs="0">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                   &lt;attribute ref="{}Visibility"/>
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element ref="{}Unit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}Operation default="leave""/>
 *       &lt;attribute ref="{}Reviewable"/>
 *       &lt;attribute ref="{}ValidFrom"/>
 *       &lt;attribute ref="{}ValidTo"/>
 *       &lt;attribute ref="{}Visibility"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitType", propOrder = {
    "id",
    "parentUnitId",
    "orgNo",
    "name",
    "management",
    "descriptionOrImageOrAddress",
    "unit"
})
public class UnitType {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "ParentUnitId")
    protected String parentUnitId;
    @XmlList
    @XmlElement(name = "OrgNo")
    protected List<String> orgNo;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Management")
    protected UnitType.Management management;
    @XmlElements({
        @XmlElement(name = "E-alias", type = EAliasType.class),
        @XmlElement(name = "Locality", type = UnitType.Locality.class),
        @XmlElement(name = "BusinessClassification", type = UnitType.BusinessClassification.class),
        @XmlElement(name = "VisitingConditions", type = UnitType.VisitingConditions.class),
        @XmlElement(name = "Person", type = PersonType.class),
        @XmlElement(name = "Telephone", type = TelephoneType.class),
        @XmlElement(name = "Address", type = Address.class),
        @XmlElement(name = "Image", type = UnitType.Image.class),
        @XmlElement(name = "Description", type = Description.class)
    })
    protected List<Object> descriptionOrImageOrAddress;
    @XmlElement(name = "Unit")
    protected List<Unit> unit;
    @XmlAttribute(name = "Operation")
    protected String operation;
    @XmlAttribute(name = "Reviewable")
    protected Boolean reviewable;
    @XmlAttribute(name = "ValidFrom")
    protected XMLGregorianCalendar validFrom;
    @XmlAttribute(name = "ValidTo")
    protected XMLGregorianCalendar validTo;
    @XmlAttribute(name = "Visibility")
    protected String visibility;

    /**
     * An official identity of the unit.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * An official identity of the unit.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentUnitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentUnitId() {
        return parentUnitId;
    }

    /**
     * Sets the value of the parentUnitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentUnitId(String value) {
        this.parentUnitId = value;
    }

    /**
     * Gets the value of the orgNo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orgNo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrgNo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrgNo() {
        if (orgNo == null) {
            orgNo = new ArrayList<String>();
        }
        return this.orgNo;
    }

    /**
     * The name of the unit.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * The name of the unit.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the management property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType.Management }
     *     
     */
    public UnitType.Management getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType.Management }
     *     
     */
    public void setManagement(UnitType.Management value) {
        this.management = value;
    }

    /**
     * Gets the value of the descriptionOrImageOrAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptionOrImageOrAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptionOrImageOrAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EAliasType }
     * {@link UnitType.Locality }
     * {@link UnitType.BusinessClassification }
     * {@link UnitType.VisitingConditions }
     * {@link PersonType }
     * {@link TelephoneType }
     * {@link Address }
     * {@link UnitType.Image }
     * {@link Description }
     * 
     * 
     */
    public List<Object> getDescriptionOrImageOrAddress() {
        if (descriptionOrImageOrAddress == null) {
            descriptionOrImageOrAddress = new ArrayList<Object>();
        }
        return this.descriptionOrImageOrAddress;
    }

    /**
     * Gets the value of the unit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the unit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Unit }
     * 
     * 
     */
    public List<Unit> getUnit() {
        if (unit == null) {
            unit = new ArrayList<Unit>();
        }
        return this.unit;
    }

    /**
     * Defines the operation to perform on information of the Unit: create, remove, update, leave.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        if (operation == null) {
            return "leave";
        } else {
            return operation;
        }
    }

    /**
     * Defines the operation to perform on information of the Unit: create, remove, update, leave.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Indicates if the unit or organization should be reviewable in applicable media and channels.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReviewable() {
        if (reviewable == null) {
            return false;
        } else {
            return reviewable;
        }
    }

    /**
     * Indicates if the unit or organization should be reviewable in applicable media and channels.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReviewable(Boolean value) {
        this.reviewable = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * Sets the value of the visibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisibility(String value) {
        this.visibility = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BCCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="BCName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{}Visibility"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bcCode",
        "bcName"
    })
    public static class BusinessClassification {

        @XmlElement(name = "BCCode", required = true)
        protected String bcCode;
        @XmlElement(name = "BCName")
        protected String bcName;
        @XmlAttribute(name = "Visibility")
        protected String visibility;

        /**
         * Gets the value of the bcCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBCCode() {
            return bcCode;
        }

        /**
         * Sets the value of the bcCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBCCode(String value) {
            this.bcCode = value;
        }

        /**
         * Gets the value of the bcName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBCName() {
            return bcName;
        }

        /**
         * Sets the value of the bcName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBCName(String value) {
            this.bcName = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}Label"/>
     *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{}Visibility"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "label",
        "fileName"
    })
    public static class Image {

        @XmlElement(name = "Label", required = true)
        protected String label;
        @XmlElement(name = "FileName", required = true)
        protected String fileName;
        @XmlAttribute(name = "Visibility")
        protected String visibility;

        /**
         * The name, title or caption of the image. Should be possible to publish in different media.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * The name, title or caption of the image. Should be possible to publish in different media.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the fileName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileName() {
            return fileName;
        }

        /**
         * Sets the value of the fileName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileName(String value) {
            this.fileName = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute ref="{}Visibility"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Locality {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Visibility")
        protected String visibility;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute ref="{}Visibility"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Management {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Visibility")
        protected String visibility;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VisitingHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DropInHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VisitingRules" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Route" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{}Visibility"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "visitingHours",
        "dropInHours",
        "visitingRules",
        "route"
    })
    public static class VisitingConditions {

        @XmlElement(name = "VisitingHours")
        protected String visitingHours;
        @XmlElement(name = "DropInHours")
        protected String dropInHours;
        @XmlElement(name = "VisitingRules")
        protected String visitingRules;
        @XmlElement(name = "Route")
        protected Object route;
        @XmlAttribute(name = "Visibility")
        protected String visibility;

        /**
         * Gets the value of the visitingHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisitingHours() {
            return visitingHours;
        }

        /**
         * Sets the value of the visitingHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisitingHours(String value) {
            this.visitingHours = value;
        }

        /**
         * Gets the value of the dropInHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDropInHours() {
            return dropInHours;
        }

        /**
         * Sets the value of the dropInHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDropInHours(String value) {
            this.dropInHours = value;
        }

        /**
         * Gets the value of the visitingRules property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisitingRules() {
            return visitingRules;
        }

        /**
         * Sets the value of the visitingRules property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisitingRules(String value) {
            this.visitingRules = value;
        }

        /**
         * Gets the value of the route property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getRoute() {
            return route;
        }

        /**
         * Sets the value of the route property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setRoute(Object value) {
            this.route = value;
        }

        /**
         * Gets the value of the visibility property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisibility() {
            return visibility;
        }

        /**
         * Sets the value of the visibility property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisibility(String value) {
            this.visibility = value;
        }

    }

}
