//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 08:35:46 AM CEST 
//


package se.vgregion.kivtools.hriv.intsvc.ws.domain.sahlgrenska;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isConcatenated" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="concatenatedAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Visit"/>
 *               &lt;enumeration value="Goods"/>
 *               &lt;enumeration value="Delivery"/>
 *               &lt;enumeration value="Post"/>
 *               &lt;enumeration value="Billing"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GeoCoordinates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Xpos" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
 *                   &lt;element name="Ypos" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Label" minOccurs="0"/>
 *         &lt;element name="StreetName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StreetNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Box" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostCode" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" minOccurs="0"/>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "isConcatenated",
    "concatenatedAddress",
    "type",
    "geoCoordinates",
    "label",
    "streetName",
    "streetNumber",
    "floor",
    "box",
    "postCode",
    "city"
})
public class AddressType {

    protected boolean isConcatenated;
    @XmlElement(required = true)
    protected String concatenatedAddress;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "GeoCoordinates")
    protected AddressType.GeoCoordinates geoCoordinates;
    @XmlElement(name = "Label")
    protected String label;
    @XmlElement(name = "StreetName")
    protected String streetName;
    @XmlElement(name = "StreetNumber")
    protected String streetNumber;
    @XmlElement(name = "Floor")
    protected String floor;
    @XmlElement(name = "Box")
    protected String box;
    @XmlList
    @XmlElement(name = "PostCode")
    protected List<String> postCode;
    @XmlElement(name = "City")
    protected String city;

    /**
     * Gets the value of the isConcatenated property.
     * 
     */
    public boolean isIsConcatenated() {
        return isConcatenated;
    }

    /**
     * Sets the value of the isConcatenated property.
     * 
     */
    public void setIsConcatenated(boolean value) {
        this.isConcatenated = value;
    }

    /**
     * Gets the value of the concatenatedAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcatenatedAddress() {
        return concatenatedAddress;
    }

    /**
     * Sets the value of the concatenatedAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcatenatedAddress(String value) {
        this.concatenatedAddress = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the geoCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType.GeoCoordinates }
     *     
     */
    public AddressType.GeoCoordinates getGeoCoordinates() {
        return geoCoordinates;
    }

    /**
     * Sets the value of the geoCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType.GeoCoordinates }
     *     
     */
    public void setGeoCoordinates(AddressType.GeoCoordinates value) {
        this.geoCoordinates = value;
    }

    /**
     * Can represent name, title, unitname or other
     * 						lables of the address
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Can represent name, title, unitname or other
     * 						lables of the address
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the streetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * Sets the value of the streetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetName(String value) {
        this.streetName = value;
    }

    /**
     * Gets the value of the streetNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetNumber() {
        return streetNumber;
    }

    /**
     * Sets the value of the streetNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetNumber(String value) {
        this.streetNumber = value;
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    /**
     * Gets the value of the box property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBox() {
        return box;
    }

    /**
     * Sets the value of the box property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBox(String value) {
        this.box = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the postCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPostCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPostCode() {
        if (postCode == null) {
            postCode = new ArrayList<String>();
        }
        return this.postCode;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Xpos" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
     *         &lt;element name="Ypos" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xpos",
        "ypos"
    })
    public static class GeoCoordinates {

        @XmlList
        @XmlElement(name = "Xpos", required = true)
        protected List<String> xpos;
        @XmlList
        @XmlElement(name = "Ypos", required = true)
        protected List<String> ypos;

        /**
         * Gets the value of the xpos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the xpos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getXpos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getXpos() {
            if (xpos == null) {
                xpos = new ArrayList<String>();
            }
            return this.xpos;
        }

        /**
         * Gets the value of the ypos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ypos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getYpos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getYpos() {
            if (ypos == null) {
                ypos = new ArrayList<String>();
            }
            return this.ypos;
        }

    }

}
