//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.17 at 08:35:46 AM CEST 
//


package se.vgregion.kivtools.hriv.intsvc.ws.domain.sahlgrenska;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;



/**
 * <p>Java class for UnitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Id"/>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Name"/>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Description" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Image" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://vgregion.se/hriv/schemas}Label"/>
 *                   &lt;element name="Filename" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Address" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Telephone" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}E-alias" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="VisitingConditions" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="TelephoneHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VisitingHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DropInHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="VisitingRules" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MvkEnable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Management" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BusinessClassification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Person" type="{http://vgregion.se/hriv/schemas}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Locality" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://vgregion.se/hriv/schemas}Unit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitType", propOrder = {
    "id",
    "name",
    "description",
    "image",
    "address",
    "telephone",
    "eAlias",
    "visitingConditions",
    "mvkEnable",
    "management",
    "businessClassification",
    "person",
    "locality",
    "unit"
})
public class UnitType {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Description")
    protected List<Description> description;
    @XmlElement(name = "Image")
    protected List<UnitType.Image> image;
    @XmlElement(name = "Address")
    protected List<Address> address;
    @XmlElement(name = "Telephone")
    protected List<TelephoneType> telephone;
    @XmlElement(name = "E-alias")
    protected List<EAliasType> eAlias;
    @XmlElement(name = "VisitingConditions")
    protected List<UnitType.VisitingConditions> visitingConditions;
    @XmlElement(name = "MvkEnable")
    protected boolean mvkEnable;
    @XmlElement(name = "Management")
    protected UnitType.Management management;
    @XmlElement(name = "BusinessClassification")
    protected List<UnitType.BusinessClassification> businessClassification;
    @XmlElement(name = "Person")
    protected List<PersonType> person;
    @XmlElement(name = "Locality")
    protected UnitType.Locality locality;
    @XmlElement(name = "Unit", required = true)
    protected Unit unit;

    /**
     * An official identity of the unit
     * 					
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * An official identity of the unit
     * 					
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * The name of the unit
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * The name of the unit
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Free text description of the unit or
     * 						information related to the unit Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitType.Image }
     * 
     * 
     */
    public List<UnitType.Image> getImage() {
        if (image == null) {
            image = new ArrayList<UnitType.Image>();
        }
        return this.image;
    }

    /**
     * Represents an address
     * 					Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Address }
     * 
     * 
     */
    public List<Address> getAddress() {
        if (address == null) {
            address = new ArrayList<Address>();
        }
        return this.address;
    }

    /**
     * Telephone contact information related to
     * 						the unit.Gets the value of the telephone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TelephoneType }
     * 
     * 
     */
    public List<TelephoneType> getTelephone() {
        if (telephone == null) {
            telephone = new ArrayList<TelephoneType>();
        }
        return this.telephone;
    }

    /**
     * Contact information related to the unit
     * 						such as e-mail, web addresses etc.Gets the value of the eAlias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eAlias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EAliasType }
     * 
     * 
     */
    public List<EAliasType> getEAlias() {
        if (eAlias == null) {
            eAlias = new ArrayList<EAliasType>();
        }
        return this.eAlias;
    }

    /**
     * Gets the value of the visitingConditions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visitingConditions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisitingConditions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitType.VisitingConditions }
     * 
     * 
     */
    public List<UnitType.VisitingConditions> getVisitingConditions() {
        if (visitingConditions == null) {
            visitingConditions = new ArrayList<UnitType.VisitingConditions>();
        }
        return this.visitingConditions;
    }

    /**
     * Gets the value of the mvkEnable property.
     * 
     */
    public boolean isMvkEnable() {
        return mvkEnable;
    }

    /**
     * Sets the value of the mvkEnable property.
     * 
     */
    public void setMvkEnable(boolean value) {
        this.mvkEnable = value;
    }

    /**
     * Gets the value of the management property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType.Management }
     *     
     */
    public UnitType.Management getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType.Management }
     *     
     */
    public void setManagement(UnitType.Management value) {
        this.management = value;
    }

    /**
     * Gets the value of the businessClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the businessClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBusinessClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnitType.BusinessClassification }
     * 
     * 
     */
    public List<UnitType.BusinessClassification> getBusinessClassification() {
        if (businessClassification == null) {
            businessClassification = new ArrayList<UnitType.BusinessClassification>();
        }
        return this.businessClassification;
    }

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getPerson() {
        if (person == null) {
            person = new ArrayList<PersonType>();
        }
        return this.person;
    }

    /**
     * Gets the value of the locality property.
     * 
     * @return
     *     possible object is
     *     {@link UnitType.Locality }
     *     
     */
    public UnitType.Locality getLocality() {
        return locality;
    }

    /**
     * Sets the value of the locality property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitType.Locality }
     *     
     */
    public void setLocality(UnitType.Locality value) {
        this.locality = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link Unit }
     *     
     */
    public Unit getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unit }
     *     
     */
    public void setUnit(Unit value) {
        this.unit = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class BusinessClassification {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://vgregion.se/hriv/schemas}Label"/>
     *         &lt;element name="Filename" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "label",
        "filename"
    })
    public static class Image {

        @XmlElement(name = "Label", required = true)
        protected String label;
        @XmlElement(name = "Filename", required = true)
        protected Object filename;

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setFilename(Object value) {
            this.filename = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Locality {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Management {

        @XmlValue
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="TelephoneHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VisitingHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DropInHours" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="VisitingRules" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class VisitingConditions {

        @XmlElement(name = "TelephoneHours")
        protected String telephoneHours;
        @XmlElement(name = "VisitingHours")
        protected String visitingHours;
        @XmlElement(name = "DropInHours")
        protected String dropInHours;
        @XmlElement(name = "VisitingRules")
        protected String visitingRules;

        /**
         * Gets the value of the telephoneHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephoneHours() {
            return telephoneHours;
        }

        /**
         * Sets the value of the telephoneHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephoneHours(String value) {
            this.telephoneHours = value;
        }

        /**
         * Gets the value of the visitingHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisitingHours() {
            return visitingHours;
        }

        /**
         * Sets the value of the visitingHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisitingHours(String value) {
            this.visitingHours = value;
        }

        /**
         * Gets the value of the dropInHours property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDropInHours() {
            return dropInHours;
        }

        /**
         * Sets the value of the dropInHours property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDropInHours(String value) {
            this.dropInHours = value;
        }

        /**
         * Gets the value of the visitingRules property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVisitingRules() {
            return visitingRules;
        }

        /**
         * Sets the value of the visitingRules property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVisitingRules(String value) {
            this.visitingRules = value;
        }

    }

}
