//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.07 at 06:44:06 PM CEST 
//


package se.vgregion.kivtools.search.svc.push.impl.eniro.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.knowit.springdemo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Telephone_QNAME = new QName("", "Telephone");
    private final static QName _EAlias_QNAME = new QName("", "E-alias");
    private final static QName _Id_QNAME = new QName("", "Id");
    private final static QName _Label_QNAME = new QName("", "Label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.knowit.springdemo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link UnitType.BusinessClassification }
     * 
     */
    public UnitType.BusinessClassification createUnitTypeBusinessClassification() {
        return new UnitType.BusinessClassification();
    }

    /**
     * Create an instance of {@link AddressType.GeoCoordinates }
     * 
     */
    public AddressType.GeoCoordinates createAddressTypeGeoCoordinates() {
        return new AddressType.GeoCoordinates();
    }

    /**
     * Create an instance of {@link UnitType.Management }
     * 
     */
    public UnitType.Management createUnitTypeManagement() {
        return new UnitType.Management();
    }

    /**
     * Create an instance of {@link UnitType.Image }
     * 
     */
    public UnitType.Image createUnitTypeImage() {
        return new UnitType.Image();
    }

    /**
     * Create an instance of {@link UnitType.Locality }
     * 
     */
    public UnitType.Locality createUnitTypeLocality() {
        return new UnitType.Locality();
    }

    /**
     * Create an instance of {@link EAliasType }
     * 
     */
    public EAliasType createEAliasType() {
        return new EAliasType();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link TelephoneType }
     * 
     */
    public TelephoneType createTelephoneType() {
        return new TelephoneType();
    }

    /**
     * Create an instance of {@link UnitType.VisitingConditions }
     * 
     */
    public UnitType.VisitingConditions createUnitTypeVisitingConditions() {
        return new UnitType.VisitingConditions();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelephoneType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Telephone")
    public JAXBElement<TelephoneType> createTelephone(TelephoneType value) {
        return new JAXBElement<TelephoneType>(_Telephone_QNAME, TelephoneType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EAliasType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "E-alias")
    public JAXBElement<EAliasType> createEAlias(EAliasType value) {
        return new JAXBElement<EAliasType>(_EAlias_QNAME, EAliasType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Id")
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

}
